spring:
  #配置数据源信息
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组，默认值为master
      primary: master
      #严格匹配数据源，默认使用false。 true未匹配到指定数据源时候抛出异常，false使用默认的数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mybatis_plus
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        slave_1:
          url: jdbc:mysql://localhost:3306/mybatis_plus1
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456

